version: '3.8'

services:
  notebook:
    build: .
    container_name: ml-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/app/notebooks
    command: >
      jupyter notebook --ip=0.0.0.0 --port=8888
      --no-browser --allow-root --NotebookApp.token=''
    depends_on:
      - mlflow
      - db

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.9.2
    container_name: mlflow-server
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_BACKEND_STORE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=/mlflow/artifacts
    volumes:
      - ./mlruns:/mlflow/artifacts
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: ml-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pgdata:
